name: LaTeX Auto Release

on:
  push:
    tags:
      - 'v*'   # triggers on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Install LaTeX packages (including XeLaTeX)
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-extra lacheck

      # Step 3: Lint LaTeX
      - name: Lint LaTeX
        run: lacheck card.tex

      # Step 4: Compile LaTeX to PDF (XeLaTeX)
      - name: Compile LaTeX
        run: |
          xelatex -interaction=nonstopmode card.tex
          xelatex -interaction=nonstopmode card.tex

      # Step 5: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Upload PDF
      - name: Upload PDF
        uses: softprops/action-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./card.pdf
          asset_name: card.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
