name: LaTeX Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex texlive-latex-extra

      - name: Compile LaTeX
        run: |
          xelatex -interaction=nonstopmode card.tex
          xelatex -interaction=nonstopmode card.tex

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF
        uses: softprops/action-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./card.pdf
          asset_name: card.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
